name: 'ci'

on:
  pull_request:
    types: ['opened', 'synchronize', 'reopened']

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1.1.1
        id: 'auth'
        with:
          workload_identity_provider: 'projects/350326448420/locations/global/workloadIdentityPools/pool/providers/provider'
          service_account: 'github-actions@lacolaco-activitypub.iam.gserviceaccount.com'
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-go
      - run: cp .env.example .env
      - run: yarn install
        working-directory: client
      - run: yarn build
        working-directory: client
      - run: npm run build:server

  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1.1.1
        id: 'auth'
        with:
          workload_identity_provider: 'projects/350326448420/locations/global/workloadIdentityPools/pool/providers/provider'
          service_account: 'github-actions@lacolaco-activitypub.iam.gserviceaccount.com'
      - uses: ./.github/actions/setup-go
      - run: cp .env.example .env
      - run: go mod download
      - run: go vet ./...
      # - run: go test ./...

  test-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - run: yarn install
        working-directory: client
      - run: yarn build
        working-directory: client
