name: 'ci'

on:
  pull_request:
    types: ['opened', 'synchronize', 'reopened']

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - run: pnpm run pack:server

  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1.1.1
        id: 'auth'
        with:
          workload_identity_provider: ${{ vars.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GOOGLE_DEPLOY_SERVICE_ACCOUNT }}
      - uses: ./.github/actions/setup-node
      - run: cp .env.example .env
      - run: pnpm install
      - run: pnpm run server test run

  test-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - run: pnpm install
      - run: pnpm run client build
