name: 'ci'

on:
  pull_request:
    types: ['opened', 'synchronize', 'reopened']

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  test-server:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: asia-northeast1-docker.pkg.dev/lacolaco-activitypub/cloud-run-builds/server
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1.0.0
        id: 'auth'
        with:
          workload_identity_provider: 'projects/350326448420/locations/global/workloadIdentityPools/pool/providers/provider'
          service_account: 'github-actions@lacolaco-activitypub.iam.gserviceaccount.com'
          create_credentials_file: true
      - uses: ./.github/actions/setup-go
      - name: copy env
        run: cp .env.example .env
      - name: install deps
        run: go mod download
      - run: go vet ./...
      - run: go test ./...

  test-client:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: asia-northeast1-docker.pkg.dev/lacolaco-activitypub/cloud-run-builds/server
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - name: install client deps
        working-directory: client
        run: yarn install
      - name: build client
        working-directory: client
        run: yarn build
