name: 'deployment'

on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write'


jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: google-github-actions/auth@v1.0.0
        with:
          workload_identity_provider: 'projects/350326448420/locations/global/workloadIdentityPools/pool/providers/provider'
          service_account: 'github-actions@lacolaco-activitypub.iam.gserviceaccount.com'
      - uses: google-github-actions/setup-gcloud@v0
      - uses: ./.github/actions/setup-go
      - name: Deploy to Cloud Run
        run: |
          gcloud --quiet run deploy activitypub-lacolaco-net \
          --source . \
          --execution-environment gen1 --region asia-northeast1 --platform managed --memory 128Mi