name: 'deployment'

on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy-server:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ vars.CLOUDRUN_SERVER_IMAGE_NAME }}
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: google-github-actions/auth@v1.1.1
        with:
          workload_identity_provider: ${{ vars.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GOOGLE_DEPLOY_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v1
      - run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      - uses: ./.github/actions/setup-go
      - name: build and push image
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} .
          docker push $IMAGE_NAME:${{ github.sha }}
      - name: deploy to Cloud Run
        run: |
          gcloud --quiet run deploy activitypub-lacolaco-net \
          --image $IMAGE_NAME:${{ github.sha }} \
          --allow-unauthenticated \
          --service-account ${{ vars.CLOUDRUN_SERVER_SERVICE_ACCOUNT }} \
          --set-env-vars=CLIENT_ORIGIN=${{ vars.CLIENT_ORIGIN }} \
          --set-secrets=RSA_PRIVATE_KEY=rsa_private:latest \
          --execution-environment gen1 --region asia-northeast1 --platform managed --memory 128Mi

  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: google-github-actions/auth@v1.1.1
        with:
          workload_identity_provider: ${{ vars.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GOOGLE_DEPLOY_SERVICE_ACCOUNT }}
      - uses: ./.github/actions/setup-node
      - run: yarn install
        working-directory: client
      - run: yarn build
        working-directory: client
      - name: deploy to Firebase Hosting
        run: npx firebase-tools deploy --only hosting
