name: 'deployment'

on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: asia-northeast1-docker.pkg.dev/lacolaco-activitypub/cloud-run-builds/server
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: google-github-actions/auth@v1.0.0
        with:
          workload_identity_provider: 'projects/350326448420/locations/global/workloadIdentityPools/pool/providers/provider'
          service_account: 'github-actions@lacolaco-activitypub.iam.gserviceaccount.com'
      - uses: google-github-actions/setup-gcloud@v1
      - run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/setup-node
      - name: install client deps
        working-directory: client
        run: yarn install
      - name: build client
        working-directory: client
        run: yarn build
      - name: build and push image
        run: |
          docker build -t ${{ env.IMAGE_IMAGE_NAME }}:${{ github.sha }} .
          docker push $${{ env.IMAGE_NAME }}:${{ github.sha }}
      - name: deploy to Cloud Run
        run: |
          gcloud --quiet run deploy activitypub-lacolaco-net \
          --image ${{ env.IMAGE_NAME }}:${{ github.sha }} \
          --allow-unauthenticated \
          --service-account api-service@lacolaco-activitypub.iam.gserviceaccount.com \
          --set-secrets=RSA_PRIVATE_KEY=rsa_private:latest \
          --execution-environment gen1 --region asia-northeast1 --platform managed --memory 128Mi
